controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# IP Address routes
ip_address_index:
    path: /ip-addresses
    methods: [GET]
    controller: App\Controller\IpAddressController::index

ip_address_index_table_data:
    path: /ip-addresses/list/{startPage}/{limit}
    methods: [GET]
    controller: App\Controller\IpAddressController::getIpAddressTableData

ip_address_add_form:
    path: /ip-addresses/add
    methods: [GET]
    controller: App\Controller\IpAddressController::add

ip_address_add_form_submit:
    path: /ip-addresses
    methods: [POST]
    controller: App\Controller\IpAddressController::addSubmit

ip_address_edit_form:
    path: /ip-addresses/{id}
    methods: [GET]
    controller: App\Controller\IpAddressController::edit

ip_address_edit_form_submit:
    path: /ip-addresses/{id}
    methods: [PUT]
    controller: App\Controller\IpAddressController::editSubmit