controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# IP Address routes
ip_address_index:
    path: /ip-addresses
    methods: [GET]
    controller: App\Controller\IpAddressController::index